controller_manager_ns: pr2_controller_manager
controller_list:
  - name: ""
    ns: joint_trajectory_action
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
