mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/base.stl"
    offset:
      yaw: 3.14159265359

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/shoulder.stl"
    offset:
      yaw: 3.14159265359

  upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/upper_arm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/upper_arm.stl"
    offset:
      z: 0.1198 # shoulder_offset measured from model
      roll: 1.57079632679
      yaw: -1.57079632679

  forearm:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/forearm.stl"
    offset:
      z: 0.0275 # elbow_offset measured from model
      roll: 1.57079632679
      yaw: -1.57079632679

  wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/wrist1.stl"
    offset:
      z: -0.085
      roll: 1.57079632679

  wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/wrist2.stl"
    offset:
      z: -0.085

  wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur3/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur3/collision/wrist3.stl"
    offset:
      z: -0.082
      roll: 1.57079632679
