# Joints limits
#
# Sources:
#
#  - Universal Robots e-Series, User Manual, UR5e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69091/99404_UR5e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
limits:
  shoulder_pan:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.14159265359
    effort: 150.0
  shoulder_lift:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.14159265359
    effort: 150.0
  elbow_joint:
    # we artificially limit this joint to half it's actual joint limit to avoid
    # (MoveIt/OMPL) planning problems, as due to the physical construction of
    # the robot, it's impossible to rotate the 'elbow_joint' over more than
    # approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.14159265359
    effort: 150.0
  wrist_1:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.14159265359
    effort: 28.0
  wrist_2:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.14159265359
    effort: 28.0
  wrist_3:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.14159265359
    effort: 28.0
