mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/base.stl"
    offset:
      yaw: 3.14159265359

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/shoulder.stl"
    offset:
      yaw: 3.14159265359

  upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/upper_arm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/upper_arm.stl"
    offset:
      z: 0.138 # shoulder_offset measured from model
      roll: 1.57079632679
      yaw: -1.57079632679

  forearm:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/forearm.stl"
      offset:
      z: 0.007 # elbow_offset measured from model
      roll: 1.57079632679
      yaw: -1.57079632679

  wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/wrist1.stl"
    offset:
      z: -0.127
      roll: 1.57079632679

  wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/wrist2.stl"
    offset:
      z: -0.0997

  wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/collision/wrist3.stl"
    offset:
      z: -0.0989
      roll: 1.57079632679
